# Placeholder:
# {cps}: CPS đang đánh vào server

webhook:
  url: ""
  username: "NullCordX Stats"
  avatar: "https://cdn.discordapp.com/avatars/541245686478536726/47c730c2798cc7722cf29c2086706290.png"
  content: "[{time}] Attack detected (true) - CPS/Blocked: **{cps}**"